version: '3.8'

services:
  sales_database:
    image: shandytp/amazon-sales-data-docker-db:latest
    container_name: sales_database
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - 5433:5432
    volumes:
      - postgre_sales_database:/var/lib/postgresql/data

volumes:
  postgre_sales_database: 