version: '3.8'

services:
  xyz_data_warehouse:
    image: postgres:latest
    container_name: xyz_data_warehouse
    restart: on-failure
    environment:
      - POSTGRES_USER=$POSTGRES_USER_LOAD
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD_LOAD
      - POSTGRES_DB=$POSTGRES_DB_LOAD
    ports:
      - 5434:5432
    volumes:
      - data_warehouse_vol:/var/lib/postgresql/data

volumes:
  data_warehouse_vol:
    name: data_warehouse_vol